# Generated by Django 5.0 on 2023-12-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='likes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
