# Generated by Django 5.0 on 2023-12-16 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('pronouns', models.CharField(max_length=15)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
