# Generated by Django 5.0 on 2023-12-19 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_id',
        ),
    ]
