# Generated by Django 5.0 on 2023-12-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_user_profile_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
